version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_username=$DB_username
      - DB-password=$DB_password
      - DB_host=db
      - PORT=$PORT
      - DB_database=$DB_database
    ports:
      - "80:8080"
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_username
      - POSTGRES_PASSWORD=$DB_password
      - POSTGRES_DB=$DB_database
    ports:
      - "5432:5432"
    volumes:     
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: